---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -Rf css $DEPLOYPATH
    - /bin/cp -Rf js $DEPLOYPATH
    - /bin/cp -Rf assets $DEPLOYPATH
    - /bin/cp -Rf v $DEPLOYPATH
    - /bin/cp -f robots.txt $DEPLOYPATH
    - /bin/cp -f sitemap.xml $DEPLOYPATH
